# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-31 10:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth_id', models.CharField(default=None, max_length=40)),
                ('username', models.CharField(default=None, max_length=30)),
            ],
            options={
                'db_table': 'account',
            },
        ),
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(default=None, max_length=40)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms_api.Account')),
            ],
            options={
                'db_table': 'phone_number',
            },
        ),
    ]
